### ISSUE TITLE
K8S job

### ISSUE THREAD

**Issue by itsecforu** [golismero/golismero#58]
Hey Folks!
Trying to start container into my cluster like that:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    spec:
      containers:
        - name: job
          image: treemo/golismero 
          args:
            - /bin/sh
            - -c
            - golismero scan -o report.hmtl https://mytarget.com**
      restartPolicy: Never
```
But i go errror:

[```
!] GoLismero: I don't know what to do with this: golismero scan -o report.html  https://mytarget.com
[!] GoLismero: Error: Failed to add new audit, reason: I don't know what to do with this: golismero scan -o report.html  https://mytarget.com
GoLismero finished at 2021-04-15 06:27:30.252147 UTC

```
Can you tell me what I do incorrect?
